sonar.projectKey=noteverse
sonar.projectName=Noteverse
sonar.host.url=http://localhost:9000

sonar.sources=backend/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.config.js,**/*.config.cjs

sonar.tests=backend/test,frontend/test
sonar.test.inclusions=**/*Test.js,**/*Test.jsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info